POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Rahasäiliö",
    "author": "Aku Ankka",
    "url": "www.google.com",
    "likes": "500",
    "userId": "654d1f83ce57b717ab52942b"
}